version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - '5433:5432'  # Mapeia para 5433 no host para evitar conflitos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pedro123  
      POSTGRES_DB: postgres     
    volumes:
      - universidade_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      app-network:
        ipv4_address: 172.20.0.2

  web:
    build: .
    container_name: postgres_db
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:pedro123@db:5432/postgres_db" 
    volumes:
      - .:/app
    networks:
      app-network:
        ipv4_address: 172.20.0.3
    restart: unless-stopped

volumes:
  universidade_postgres_data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16